[build]
  command = "yarn build"
  functions = "api"
  publish = "build"

[dev]
  framework = "#custom"
  command = "yarn serve"
  port = 3000
  targetPort = 8080
  publish = "build"
  autoLaunch = true